spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:prod_db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      #format_sql: true
logging:
  level:
    ru.otus: INFO