CREATE TABLE AUTHORS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKS_AUTHORS (
    BOOK_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);

CREATE TABLE BOOKS_GENRES (
    BOOK_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    PRIMARY KEY (BOOK_ID, GENRE_ID)
);

CREATE TABLE COMMENTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BOOK_ID BIGINT NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID)
);